js/pulse.js
Fixes #3 
Turned out this is just a simple fix 👯
=> Got rid of Sheetsu, bye

js/pulse.js
=> Converted tabs into spaces

LICENSE
=> Added MPL v2 LICENSE to repo

css/projects.css, js/pulse.js
Related to #16 (more cleanup work to come in follow-up PRs)
For my PR reviewer (I'm 👀 at @cadecairos @acabunoc ), at a glance there seems to be lots of code changes but if you review the PR commit by commit it should make the PR review fairly simple. 😉
=> Some code cleanup

css/projects.css, index.html, js/project-card.js, js/pulse.js
Fixes #28 
@cadecairos / @acabunoc this should be tiny PR to review. 👍
=> Removed swipe-to-dismiss code

js/project-card.js, js/pulse.js
Fixes #37 
@cadecairos / @acabunoc review plz? 🐹
=> Made `colors` property of PulseMaker

index.html, js/notifier.js, js/pulse.js
Fixes #29 
@acabunoc this is similar to what I did in PR https://github.com/mozilla/network-pulse/pull/25. 
- 1st commit https://github.com/mozilla/network-pulse/commit/40a18092d66ea6b92a9868d2b583580e9387eba3 is just changing the way the object is created (using object literal instead)
- 2nd commit https://github.com/mozilla/network-pulse/commit/a1b3e50eaa6e1f833f812355fbff72fb66bb2995 I renamed the object `notify` to `Notifier`. And changed occurrences of `Notifier` within `Notifier` itself to `this`.
=> Notifier module

css/projects.css, index.html, js/project-card.js, js/pulse.js, js/utility.js
Fixes #39 
@acabunoc / @cadecairos review plz 🌹 
Note that I can't figure out how to get the direct link preselected on mobile. When this PR gets merged I'll create a follow-up ticket for that.
=> Added share button

js/utility.js
=> Fixed share link bug for gh-pages links

index.html
=> Updated footer link

index.html, js/project-card.js
=> Cleaned up project-card.js by using lodash template

css/projects.css, index.html, js/detail-view-manager.js, js/project-card.js, js/pulse.js
This needs to wait for PR https://github.com/mozilla/network-pulse/pull/47 is landed first. When PR https://github.com/mozilla/network-pulse/pull/47 is landed I'll rebase & update this PR.
Fixes #45 - improved detail view
=> Improved Detail View

index.html, js/detail-view-manager.js, js/favourites-manager.js, js/project-card.js, js/pulse.js
This PR is based on PR #47 and PR https://github.com/mozilla/network-pulse/pull/50. I will rebase this branch once they are merged into `gh-pages`.
This fixes #51.
/cc @acabunoc @cadecairos
=> FavouritesManager

css/projects.css, index.html, js/favourites-manager.js, js/project-card.js, js/pulse.js
=> Fixed lettercase for `id` and `class` attributes

css/projects.css
=> Fixed single column layout bug on Safari

css/projects.css, index.html, js/detail-view-manager.js, js/project-card.js, js/pulse.js, svg/icon-add.svg, svg/icon-search.svg
Fixes #90 
Design: https://github.com/mozilla/network-pulse/issues/59
=> New header, nav, footer look

index.html
=> Added impact story link to footer

js/favourites-manager.js
=> Added 'pulse-' as localStorage key prefix for 'favourites'

css/projects.css, index.html, js/pulse.js
=> Added "no search result" view

css/projects.css, index.html
=> Removed 'prototype' banner

css/projects.css
=> Removed input field outline

css/projects.css
=> Close form button should be visible now

css/projects.css
=> Single post should be centered

css/projects.css, index.html
=> Use Fira Sans instead of Open Sans

css/projects.css
=> Fixed CSS margin glitch in Project Card

js/pulse.js
=> Turned off auto refresh for now

css/projects.css, index.html, svg/icon-link-selected.svg
=> Hover state improvments

css/projects.css
=> Responsive footer layout

css/projects.css
=> Adjusted 'add new' button location on mobile

css/projects.css, index.html, js/pulse.js, js/views-manager.js
=> "Project not found" screen

js/notifier.js, js/pulse.js
Fixes #62.
PR https://github.com/mozilla/network-pulse/pull/124 turns off auto refresh & updates (for now) while this PR fixes the currently broken notification logic
To test
- make sure `FEATURE.notify` in `pulse.js` is set to `true`
- you can lower `REFRESH_INTERVAL` if you are like me who's impatient 😉 
- try submitting a new project, return to the app, and see you get a desktop notification for that newly added project
=> Fixed notification bug

css/projects.css, index.html, js/pulse.js, js/search.js, js/views-manager.js
Fixes #99 (UI), #121 (functionalities)
@acabunoc This PR is big so plz take your time to review it. I'll start putting comments and notes after I get my ☕ .
=> Search UI & funtionalities

js/utility.js, js/views-manager.js
Fixes #169 
purely code cleanup by making use of the [Location API](https://developer.mozilla.org/en-US/docs/Web/API/Location)
@cadecairos @acabunoc review plz? 😄
=> Cleaned up utility.js

js/utility.js
Fixes #80 . This is implemented on top of PR #173. Please review #173 first 😉 See https://github.com/mozilla/network-pulse/pull/174/commits/c7a3ae89d8e91d68804b5891c67c8306edbad9ae for code changes introduced in this PR.
=> Shortened share link

index.html, js/project-card.js
=> Renamed creator to creators

css/projects.css, index.html, js/pulse.js
Fixes #128
@acabunoc @cadecairos tiny PR for review!
=> Fixed scrollbar bug in embedded form

index.html
=> Updated search hint text

css/projects.css
=> Removed heart icon's hover state for now

js/pulse.js
=> Fixed syntax bug in pulse.js

js/search.js, js/views-manager.js
Fixes #181 
/cc @cadecairos @acabunoc
=> Search enhancement

js/search.js, js/utility.js, js/views-manager.js
Fixes #67 
On Search mode...
/cc @cadecairos @acabunoc
=> Included search terms as URL query string

css/mofo-bootstrap.css, css/projects.css, index.html
=> Added mofo-bootstrap

css/projects.css
implemented design tweaks suggested in https://github.com/mozilla/network-pulse/pull/213#issuecomment-248429425
=> Design tweaks

css/projects.css
=> Text colour adjustment

package.json
=> Change project license from MIT to MPL-2.0

components/project-card/project-card.jsx, scss/main.scss
=> Creator and timestamp display

components/project-card/project-card.jsx, components/project-card/project-card.scss, components/project-list/project-list.jsx, scss/main.scss
=> Share button

README.md
=> Updated README.md with upcoming v2 info

index.html
=> Link to fira.css

pages/search/search.jsx, pages/search/search.scss
=> Persistant keyboard bug on mobile & styling fixes for dismiss button

js/pulse.js
=> Made splash page stay longer

pages/favs.jsx
=> Fixed typo

components/project-list/project-list.jsx, components/project-list/project-list.scss, pages/search/search.jsx, pages/search/search.scss
=> Search page layout

main.jsx, scss/main.scss
=> Added splash screen to v2 app

components/project-card/project-card.jsx, components/project-card/project-card.scss
=> Links to detail view

components/project-card/project-card.jsx, components/project-list/project-list.jsx, js/service.js, pages/entry.jsx, pages/favs.jsx, pages/featured.jsx
Fixes #319
Note that for now client side filtering is still needed for the search functionality to work.
=> Remove client side filtering

components/project-card/project-card.jsx, components/project-list/project-list.jsx, js/utility.js, pages/entry.jsx
=> Make sure <ProjectCard> are getting the props it should get

components/project-list/project-list.jsx, js/service.js
=> Make sure we are passing the right params props to <ProjectList>

js/service.js
=> Object.assign improvements

package.json
Fixes #323 
@Pomax Do you mind testing on Windows? I've never developed on Windows machine before... I'm just worried it would take me a while to have the basics set up in Windows VM. 🙄
=> Used browerlist package instead of passing options to cli command directly

css/projects.css, index.html, js/project-list-item.js, js/views-manager.js
#288
This branch now resolves the merge conflict
=> Add heart in favs list

js/app-user.js, js/localstorage.js, routes.jsx
=> Show splash screen on user's first visit only

scss/main.scss
this was supposed to be removed looooong time ago but i forgot about it until now
=> removed overflow hidden CSS rule on #app

package.json, webpack.config.js, webpack.server.config.js
Fixes #352
Changes made based on this migration guide: https://webpack.js.org/guides/migrating/
=> Upgraded to webpack v2

components/issue-selector/issue-selector.scss, components/project-list/project-list.jsx, pages/add/add.jsx, pages/bookmarks.jsx, pages/search/search.jsx, scss/main.scss
@alanmoo I thought about doing the suggestion you have on https://github.com/mozilla/network-pulse/pull/348#discussion_r100635697 but that means we are wrapping all project cards in ONE `.row` element... which doesn't sound right to me? If we wanna make use of `.row` class we should wrap projects in groups of 3 (can be tackled as a separate PR if needed).
=> 'load more' button CSS improvement

components/issue-selector/issue-selector.jsx, components/nav-link/nav-link.jsx, components/navbar/navbar.jsx, components/project-card/project-card.jsx, components/selector-link/selector-link.jsx, main.jsx, package.json, pages/search/search.jsx
=> Added Google Analytics

README.md
=> updated README with official staging instance info

pages/entry.jsx
=> Tweaks confirmation message

routes.jsx, scss/main.scss
I'm gonna slowly cleaning up CSS in this codebase...
=> tiny css cleanup

components/footer/footer.jsx, components/footer/footer.scss, components/navbar/navbar.scss, package.json, scss/main.scss
=> MoFo unified footer

pages/add/add.jsx, pages/add/add.scss, scss/main.scss, scss/variables.scss
Fixes #374 
Will fix checkbox right margin issue separately, since it's somewhat related to `react-formbuilder` library we are using.
=> Form styling improvements

components/project-list/project-list.jsx, scss/main.scss
=> Added loading spinner animation

components/project-list/project-list.jsx
=> Added back a wrapper div that was accidentally removed

main.jsx, server.js
fixes https://github.com/mozilla/network-pulse/issues/388
=> switch to https when we're not in development mode

js/security-headers.js, package.json, server.js
Fixes #350 
@cadecairos @Pomax Is it as simple as just adding `app.use(helmet());` to `server.js` ? I thought using the [defaults](https://www.npmjs.com/package/helmet#how-it-works) should be fine but since I have limited knowledge on HTTP headers I'd like you to help verify these configs are correctly set. Thanks!
=> Use helmet

components/project-card/project-card.jsx, components/project-card/project-card.scss, scss/main.scss
Fixes #394 
list view, clip with ellipsis
detail view, show full text
=> Added "time posted" meta to project card

pages/add/add.jsx, pages/add/form/detail-info-fields.js
=> Tags not hashtags

.babelrc, README.md, package.json, webpack.config.js, webpack.server.config.js
=> Added environment variables section to README

pages/add/add.jsx, pages/add/add.scss, scss/main.scss, scss/overrides/_variables.scss
Fixes #391 
- added some margin to checkboxes (in `issues` fieldset)
- fixed misalignment of the "Add more" button (in `creators` fieldset)
- cleaned up CSS code a bit by making use classes and mixins from mofo-bootstrap / bootstrap (mostly button stylings and anchor colour)
comps for reference: https://redpen.io/nvd9c7a75f06c79e35
=> Form styling tweaks and CSS cleanup

package.json
=> 'document-env-vars' should be a dependencies, not 'devDependencies'

js/analytics.js, main.jsx
Fixes #368 
- Updated GA UA code
- Moved GA related functions to a separate file
- It should now respect user's Do Not Track preference
=> Updated GA UA code, moved GA related functions to a separate file

.eslintrc.yaml
https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-uses-react.md
=> eslint rule tweaks

package.json
=> Upgraded 'stylelint-config-standard' to v16

js/app-user.js, pages/add/add.jsx, pages/bookmarks.jsx
Fixes #343 
I pretty much just stole your suggested code @Pomax  😁
=> Registered components as user class's listeners

README.md
=> Added 'deployment' section to README

.eslintrc.yaml, README.md, components/project-list/project-list.jsx, components/project-loader/project-loader.jsx, js/build-env-config.js, js/service.js, package.json, pages/bookmarks.jsx, pages/featured.jsx, pages/issue.jsx, pages/latest.jsx, pages/search/search.jsx, routes.jsx, sample.env, server.js
=> Project list refactor. Fetch 24 projects at a time by default.

pages/search/search.jsx
=> Input box focus on search page

components/project-card/project-card.jsx, js/service.js, package.json, pages/add/add.jsx, pages/add/form/detail-info-fields.js, pages/add/form/validator.js, scss/main.scss
=> Image upload

pages/add/form/detail-info-fields.js
=> Copy tweaks

components/project-card/project-card.jsx, components/project-card/project-card.scss
=> Detail view tweaks

pages/add/add.jsx
Fixes #399 
I believe we can remove this temp fix now. 😉
=> Removed temp fix code

components/project-card/project-card.jsx, components/project-card/project-card.scss
=> Animated heart icon

manifest.json
=> manifest start url

pages/add/add.jsx
When a form passes validation and can be sent off, this change sets `disabled` on the submit button and changes its label to say "Submitting..."
=> disables the submit button when a form is posted

js/security-headers.js
Fixes #462 
@flukeout this should work. help me verify? 🍺
=> Allow manifest.json to load

components/project-list/project-list.jsx, components/project-loader/project-loader.jsx, js/app-page-settings.js, main.jsx, pages/bookmarks.jsx, routes.jsx
=> Restore list scroll position

components/project-loader/project-loader.jsx, pages/bookmarks.jsx
Fixes #429 
Based off of PR #445. This will need a rebase after PR #445 gets merged.
=> bookmarks.jsx refactor & cleanup

package.json
=> Updated node-sass to v4.5.2

package.json
=> Updated npm-run-all to ^4.0.2

README.md
revising project summary and invitation to contribute
=> updating readme info

components/project-loader/project-loader.jsx, routes.jsx
=> Added /tags and /tags/param routes

components/footer/footer.jsx
=> footer updated

index.html, package.json, pages/add/add.jsx, pages/bookmarks.jsx, pages/entry.jsx, pages/issue.jsx, pages/issues.jsx, pages/search/search.jsx, routes.jsx, server.js
Fixes #483 
`react-helmet` doc: https://github.com/nfl/react-helmet
=> More descriptive html doc title

package.json, pages/add/add.jsx, pages/add/add.scss, pages/add/form/basic-info-fields.js, pages/add/form/detail-info-fields.js
Fixes #529, #484 
- https://github.com/mozilla/network-pulse/issues/529#issue-227722578
- https://github.com/mozilla/network-pulse/issues/484#issuecomment-301199455
=> Form tweaks

components/navbar/navbar.jsx, components/navbar/navbar.scss, components/project-card/project-card.jsx, components/project-card/project-card.scss, components/project-list/project-list.jsx, pages/entry.jsx, scss/main.scss, scss/mixin.scss, scss/overrides/_variables.scss
Fixes #491... plus CSS cleanup to project cards and nav bar.
@alanmoo sorry for the not-so-small PR. I couldn't help but clean up some custom CSS code with Bootstrap classes. I've QAed them on Chrome, Firefox, and Safari and they all seem good to me. The only thing that's different from what we had before is the gutter width between project cards now is wider. Once we get the changes up on staging I will ask feedback/suggestion from designers and we can tweak styling from there.
=> More responsive cards. CSS cleanup to project cards and nav bar.

components/project-card/project-card.jsx, js/service.js, package.json, pages/add/add.jsx, pages/add/add.scss, pages/add/form/detail-info-fields.js
Fixes #482
Also addresses #545
Design and styling can be improved but let's just get the functionality live first! 😉
=> Tag suggestions on form

pages/entry.jsx
Fixes #544 
To test, add `justPostedByUser=true` query to the `entry` url. e.g., `http://localhost:3000/entry/1?justPostedByUser=true`
=> Fixes misalignment

pages/add/add.jsx, pages/bookmarks.jsx
#547 : sign in with Google feature added
=> sign in with Google

components/project-loader/project-loader.jsx
=> adding issue counter

pages/add/add.jsx
Addresses #441. There might be more work to do there, but this was a super quick fix.
=> Add an error message for form validation

pages/add/form/detail-info-fields.js
fixes https://github.com/mozilla/network-pulse/issues/562, the ninja hack way.
Ideally, this hack can be taken out again after https://github.com/i-like-robots/react-tags/issues/76 is addressed.
=> force delimiting on comma

pages/add/form/detail-info-fields.js
Fixes #576 
Don't auto focus the tag field.
=> /add page partway bug

.travis.yml, appveyor.yml, components/project-card/project-card.scss, components/project-loader/project-loader.jsx, pages/entry.jsx
Fixes https://github.com/MozillaFoundation/mofo-devops/issues/511
=> Enable Travis and Appveyor CI

README.md
=> Added a few status badges to README

components/details.jsx, components/project-card/project-card.jsx
=> Show 'published by' meta in project card

components/moderation-panel.jsx, components/project-card/project-card.jsx, components/project-loader/project-loader.jsx, js/app-user.js, js/bookmarks-manager.js, js/security-headers.js, js/service.js, pages/add/add.jsx, pages/bookmarks.jsx, pages/search/search.jsx
Fixes #310 
❗️❗️❗️ Dependent on https://github.com/mozilla/network-pulse-api/pull/156 . Don't merge this PR until we make sure https://github.com/mozilla/network-pulse-api/pull/156 is pushed on API production.
---
@Pomax there are lots of changes happening in `bookmarks.jsx` and `project-card.jsx`. It might be easier to review these 2 files by looking at the files directly instead of checking the code differences that were introduced in this PR.
=> Bookmark entries with api

js/service.js, pages/add/add.jsx, pages/add/form/detail-info-fields.js, pages/add/form/get-help-fields.js
=> Updated form with 'help types' field

components/navbar/navbar.scss
#628 : add btn color changed to black
=> changing add btn color to black

components/project-card/meta/get-involved.jsx, components/project-loader/project-loader.jsx, js/service.js, pages/issue.jsx, pages/search/search.jsx, pages/single-filter-criteria-page.jsx, pages/tag-typy-page.jsx, routes.jsx
=> Added route for '/help/typeofhelp'

components/project-card/project-card-detailed.jsx, components/project-card/project-card.scss
Related to #485 
@gvn The report correct link will only show on detail view (e.g., http://localhost:3000/entry/334) and not list view (e.g., http://localhost:3000/latest )
=> Added correction link

components/nav-link/nav-link.jsx, pages/add/submitted.jsx, routes.jsx
=> Converted a few things to ES6

package-lock.json, package.json
=> Use react-formbuilder v0.7.0

pages/add/form/detail-info-fields.js
Fixes #644 
Try
- typing in `MozFest` as the new tag and see if it gets converted to `mozfest` when you hit enter
- copying and pasting `MozFest` and see if it gets converted to `mozfest` when you hit enter
=> Check new tag's lettercase and fix it if needed

components/navbar/navbar.jsx, components/navbar/navbar.scss, index.html, package-lock.json, package.json, scss/main.scss, server.js
=> Use zilla and change footer colour to black

components/project-card/project-card.scss, pages/add/form/basic-info-fields.js
Related to #489 
- reduced font size in title from 30px to 26px
- reduced character count from 140 to 80
Tiny PR for review.
=> Reduces project title's font size and character limit

components/project-card/meta/creators.jsx, components/project-card/meta/get-involved.jsx
Relates to #645 
I have created a few entries on staging for testing (id `336` to `340`)
=> Tidy up get involved section

components/project-loader/project-loader.jsx, pages/issue.jsx
=> Don't double encode issue name

README.md, components/moderation-panel.jsx, components/project-card/project-card-simple.jsx, components/project-loader/project-loader.jsx, js/build-env-config.js, js/service.js, pages/search/search.jsx, pages/search/search.scss, routes.jsx, sample.env
Fixes #616 
❗️Before merging, make sure the new env var `LEARN_MORE_LINK` is set
=> Added featured toggle to Moderation page

pages/search/search.jsx
=> Show right set of query params in url

components/nav-link/nav-link.jsx, components/navbar/navbar.scss, scss/main.scss
=> Made nav links use Open Sans

components/form-fields/dynamic-checkbox-group.jsx, pages/add/add.scss, pages/add/form/detail-info-fields.js, pages/add/form/get-help-fields.js
Fixes #673
90% of this code is based on what we had for `class HelpTypes`. Changes introduced are mostly for generalizing var/func names.
=> Form refactor - added <DynamicCheckboxGroup>

components/nav-link/nav-link.jsx
=> Brought back missing 'Add' nav button

pages/add/form/detail-info-fields.js
Fixes https://github.com/mozilla/network-pulse/issues/599
=> Add link to internet health issues on 'create entry' form

components/form-fields/help-types.jsx, components/form-fields/issues.jsx, components/project-loader/static-project-loader.jsx, js/app-user.js, pages/add/add.scss, pages/add/form/detail-info-fields.js, pages/add/form/get-help-fields.js, pages/profile-edit/form/fields.js, pages/profile-edit/profile-edit.jsx, pages/profile-edit/profile-edit.scss, routes.jsx, scss/form.scss, scss/main.scss
https://github.com/mozilla/network-pulse/pull/679 got merged into `edit-profile-page` last week but my force push just now messed up and reset `edit-profile-page` to what's in `master`. This PR will add the missing code back.
=> Re-merging approved work to edit-profile-page

components/bio/bio.jsx, components/bio/bio.scss, components/navbar/navbar.jsx, components/navbar/navbar.scss, js/service.js, pages/profile.jsx, routes.jsx, scss/main.scss
Related to #622
**This PR is a feature branch against another feature branch `all-things-profile-related`.**
It only covers code needed to render a loggedin user's own profile view
- visit the page by clicking the "Hi, [username]" link on nav bar
- or visiting `/profile/me` directly
Everything profile related features/specs will be tackled in follow-up PRs.
=> Profile Page - render MVP view for an user's own profile

components/form-fields/dynamic-checkbox-group.jsx, components/form-fields/issues.jsx, js/form-validator.js, js/service.js, package.json, pages/add/add.scss, pages/profile-edit/form/fields.js, pages/profile-edit/profile-edit.jsx, scss/form.scss
Two ways to go the the edit profile page (make sure you are logged in first. followup PR will be filed to take care https://github.com/mozilla/network-pulse/issues/685)
- visit `/profile/me` and click on "edit profile" link under your profile pic
- visit `/myprofile` directly
Things to verify
- form is prefilled with user's current profile data
- you are able to update your profile
- form validation works
=> Edit profile - form submission

pages/profile-edit/profile-edit.jsx, scss/form.scss
Related to #703 
Just some copy changes and a margin change.
=> Addressed most of design and copy changes in the ticket

sample.env
PR for issue #689. Please review.
=> Updated PULSE_API in sample.env

components/bio/bio.jsx, pages/my-profile.jsx, pages/profile.jsx, scss/main.scss
Related to #723 
- go to http://test.example.com:3000/profile/me and test if the "Sign out" link works fine (make sure you are logged in)
=> Added sign out link to /profile/me

components/navbar/navbar.jsx, components/navbar/navbar.scss
Related to #739 
Note: 
Signing **out** from /favs seems to be [problematic](https://github.com/mozilla/network-pulse/issues/722). When you test this PR make sure you log out from "my profile" page or the "add" page. "Sign out" link on /favs page is [to be removed](https://github.com/mozilla/network-pulse/issues/734) after this PR is merged.
=> Added 'signup/sign in' link to nav bar

components/moderation-panel.jsx, components/project-card/project-card.scss, pages/search/search.scss
No mockup/comps to refer to. Just some quick fixes to fix some obvious UI flaws.
=> styling tweak for Moderation page

package.json, pages/add/add.scss, pages/add/form/detail-info-fields.js, scss/main.scss, scss/react-formbuilder.scss
@mmmavis I'm not too sure about where the CSS should go here, or whether you already had a predefined class to make the checkbox look good.
Work left: figure out how to update formbuilder such that we can put this field "in" the label for the creators. According to the comps this should go between the creators label and the creators fields, and formbuilder does not allow for that right now.
=> add 'I am the creator' checkbox to entry form

pages/bookmarks.jsx
=> Removed sign in/out from /favs page

package.json, pages/add/add.scss, pages/add/form/basic-info-fields.js
This PR adds in the character limit for "title" in a twitter style "show characters remaining" fashion:
This closes https://github.com/mozilla/network-pulse/issues/493
=> Add character limit to title

package-lock.json, package.json
Snyk identified that the superagent version we have in our package.json has a known vulnerability, but I also found that we're not using it anywhere (correct me if I'm wrong)
=> Remove unused superagent module

README.md
Fixes: #764 
Proposed changes:
- good first bug -> good first issue
- https://github.com/mozilla/network-pulse/labels/good%20first%20bug -> https://github.com/mozilla/network-pulse/labels/good%20first%20issue
=> fix: Good first bug link in README.md is invalid

components/project-card/project-card.scss
=> fix: Add background to image container for wide photos

js/service.js, pages/add/add.scss, pages/add/form/creators.js, pages/add/form/detail-info-fields.js
=> Adding autocomplete to creators

components/navbar/navbar.jsx, js/app-user.js, pages/add/add.jsx, pages/profile-edit/profile-edit.jsx
- (first commit) Related to #741 - display user's custom name if it exists. otherwise fall back to user's username
- (second commit) Related to #727 - profile edit form should include default name
=> Show user's custom name where applicable

components/project-card/meta/creators.jsx, components/project-card/project-card-detailed.jsx, components/project-card/project-card-simple.jsx, js/service.js, pages/profile.jsx
Closes #742 
I believe this is ready to review, staging API could use some data massaging but you can check http://localhost:3000/profile/5 to see the creators link working
=> Profiles show created entries

pages/add/form/creators.js
=> Make autocomplete show who has a profile already

components/bio/bio.jsx
=> Hide unused social media links on profiles

pages/add/form/detail-info-fields.js
=> Change "add creators" label

components/project-loader/project-loader.jsx
=> Proper pluralization

components/project-card/project-card-simple.jsx
=> Added a new section to display full urls on moderation view

components/nav-link/nav-link.jsx, components/navbar/navbar.jsx, components/navbar/navbar.scss
Related to #799 . I tried my best to respect the original design & not shift DOM elements around...
1. make sure you have a super long name
2. adjust browser size and see if nav bar renders okay
=> Clip long name on nav bar

pages/add/form/detail-info-fields.js
Resolves https://github.com/mozilla/network-pulse/issues/808
=> Change "Published by creator" label

components/project-card/project-card-simple.jsx
Good to bring this back @xmatthewx?
=> Show creator links on gallery pages again

package-lock.json, pages/add/submitted.jsx
=> Change copy after you post an entry

pages/add/form/auto-complete-input.js, pages/add/form/creators.js, pages/add/form/detail-info-fields.js, pages/add/form/get-help-fields.js, pages/add/form/tags.js
=> Fixed linting errors

package.json, routes.jsx
=> Scroll to top when visiting /add page

components/project-loader/project-loader.jsx, pages/bookmarks.jsx
=> Show bookmark prompt for loggedin user

pages/profile-edit/profile-edit.jsx
This PR updates the profile-edit component to es6 for #477 @mmmavis
=> update profile edit component

components/bio/bio.jsx
=> Increased 'mouseover' area of social media icons on profile page

components/project-list/project-list.jsx
=> Left align project cards

CODEOWNERS
We can adjust this as necessary, but we need something for now
=> Add a codeowners file.

components/bio/bio.jsx
=> Fixed issue tag url mapping on Profile page

routes.jsx
Thought I already fixed this... but it probably got accidentally reverted during a rebase process 🙄
=> Reduced bottom margin of a paragraph

components/bio/bio.jsx, components/issue-selector/issue-selector.scss, components/navbar/navbar.scss, components/project-card/project-card.scss, scss/main.scss, scss/mixin.scss, scss/overrides/_variables.scss
=> Unifying link styling

components/notification-bar/notification-bar.jsx, components/notification-bar/notification-bar.scss, pages/add/add.jsx, pages/add/submitted.jsx, pages/entry.jsx, scss/main.scss
Related to #867 
https://network-pulse-staging-pr-884.herokuapp.com/entry/373?justPostedByUser=true (note that the query `justPostedByUser=true` should be clear after the page gets loaded)
https://network-pulse-staging-pr-884.herokuapp.com/submitted
=> Purple notification bar + some code cleanup

components/bookmark-control.jsx
=> Unblocking heart UI

components/bio/bio.jsx, components/form-fields/dynamic-checkbox-group.jsx, components/loading-notice.jsx, components/moderation-panel.jsx, components/project-card/meta/get-involved.jsx, components/project-card/meta/thumbnail.jsx, components/project-card/project-card-detailed.jsx, components/project-card/project-card-simple.jsx, components/project-list/project-list.jsx, components/project-loader/project-loader.jsx, main.jsx, package-lock.json, package.json, pages/add/add.jsx, pages/add/form/auto-complete-input.js, pages/bookmarks.jsx, pages/issue.jsx, pages/my-profile.jsx, pages/not-found.jsx, pages/profile-edit/profile-edit.jsx, pages/public-profile.jsx, pages/search/search.jsx, pages/single-filter-criteria-page.jsx
Related to #892 
@gvn https://github.com/mozilla/network-pulse/pull/893/files?w=1 <-- the `w` query param will hide all whitespace only differences on the "files changed" page. This should make your review easier.
=> Upgraded eslint and eslint-plugin-react & fixed linting errors (all indentation related)

CODEOWNERS, PULL_REQUEST_TEMPLATE.md
I'm getting too many emails. Maybe this approach will be better.
=> Move codeowners to PR template

pages/add/add.jsx
Related issue: #804 
Summary: I have made the changes @xmatthewx .
=> Changed 'Terms Of Service' to 'Terms Of Use'

js/app-user.js, js/service.js, package.json, pages/add/form/auto-complete-input.js, pages/add/form/creators.js, pages/add/form/detail-info-fields.js, pages/add/form/tags.js, server.js, webpack.server.config.js
=> Lint all the things!

pages/profile.jsx
Related issue: #909
Summary: I have made the requested changes.
@alanmoo, please review
=> Name Added To Page Title In Profile Views

components/project-card/meta/get-involved.jsx, js/service.js, js/utility.js, pages/single-filter-criteria-page.jsx
=> Prettify helpType slug

components/project-loader/project-loader.jsx
Related issue: Issue-798
Summary: Created a state dataLoaded, which gets updated when the search promise is resolved. 
Please review this @xmatthewx
=> Fix: #798 hide search count

components/bio/bio.jsx, components/project-card/meta/creators.jsx
=> Added back missing handler

.travis.yml, appveyor.yml
Fix MozillaFoundation/mofo-devops-private#131
=> move to node lts for ci

server.js
Related issue: https://github.com/mozilla/network-pulse/issues/914
Summary: This PR adds RSS link to head.
Thanks for considering this request.
@xmatthewx Can you review this?
=> fixed #914

js/app-user.js
=> Custom name not getting displayed

js/security-headers.js
Related to #704
To get rid of these errors...
=> Resolved Twitter related CSP errors

components/hint-message/hint-message.jsx, components/profile-tab-group/profile-tab-group.jsx
Related to #955 
I hope I covered everything...
=> Profile page followup

components/profile-tab-group/profile-tab-group.jsx
=> Showed 'about' tab on profile only when there's long bio to show

js/service.js, pages/add/form/creators.js
=> Fixed creators autocomplete bug

pages/add/form/creators.js
=> Fixed creator bug in form

pages/profile-edit/form/fields.js, pages/profile-edit/profile-edit.jsx, pages/profile-edit/profile-edit.scss
Related to #920 
https://github.com/mozilla/network-pulse/pull/974/files?w=1
=> Added 'long bio' field to profile edit form

app.json
=> Missing env var for review apps

server.js
Related issue: https://github.com/MozillaFoundation/mofo-devops/issues/599
Summary: Adds an Express route that redirects to the Pulse API admin.
=> Redirect to pulse API admin

components/issue-selector/issue-selector.jsx, js/utility.js, pages/issue.jsx
Related issue: #1012 
Summary: replace 'Open Innovation' with 'Openness'
@gideonthomas Please review
=> replace 'Open Innovation' with 'Openness'

pages/profile-edit/form/fields.js
=> Added location field to profile

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/design-to-dev-handoff-.md
I copied everything directly from Foundation site repo
=> Update issue templates

assets/svg/featured.svg, components/project-card/project-card-simple.jsx, scss/main.scss, scss/overrides/_type.scss
Closes #1035
Related PR: #1050 (Rebase Issues), #1064
=> Added featured flag

app.jsx, components/form-fields/help-types.jsx, js/analytics.js, js/app-user.js, js/bookmarks-manager.js, pages/add/form/auto-complete-input.js, pages/add/form/basic-info-fields.js, pages/add/form/detail-info-fields.js, pages/add/form/tag-delimiters.js, pages/add/form/tags.js, pages/add/form/validator.js, pages/bookmarks.jsx, pages/issue.jsx, pages/moderation-search/moderation-search.jsx, pages/profile-edit/form/fields.js
Fixed more linting errors. I tried to only update the files that aren't being touched in any currently open PRs.
Fixed each file by using VS Code's auto fix linting error feature
=> Fixed more linting errors

js/security-headers.js, server.js
=> Fixing font rendering 

components/help-dropdown/help-dropdown.jsx, components/project-loader/project-loader.jsx, components/search-result-counter.jsx, pages/search/search.jsx, pages/search/search.scss, scss/main.scss
Related: #1070 
**This ticket:**
1. Updates the UX flow of dropdown vs search
2. Updates search query results styles
3. Separates dropdown component from search
**Still need to:** _(will do final tweaks on dropdown-fever branch)_
1. Make dropdown-search group responsive
=> Making separate dropdown component

components/bio/bio.jsx, components/form-fields/dynamic-checkbox-group.jsx, components/form-fields/issues.jsx, components/hint-message/hint-message.jsx, components/item-list/item-list.jsx, components/profile-about-tab/profile-about-tab.jsx, components/profile-card/profile-card.jsx, components/profile-loader/profile-loader.jsx, components/profile-project-tab/profile-project-tab.jsx, components/profile-tab-group/profile-tab-group.jsx, components/project-card/meta/description.jsx, components/project-card/meta/get-involved.jsx, components/project-card/meta/title.jsx, components/project-card/meta/why-interesting.jsx, components/project-card/project-card-detailed.jsx, components/project-card/project-card-simple.jsx, components/project-loader/project-loader.jsx, js/env-client.js, js/env-server.js, js/form-validator.js, js/localstorage.js, js/security-headers.js, js/service.js, js/utility.js, main.jsx, pages/add/submitted.jsx, pages/entry.jsx, pages/moderation.jsx, pages/profile.jsx, server.js
Same same.
---
Fixed more linting errors. I tried to only update the files that aren't being touched in any currently open PRs.
Fixed each file by using VS Code's auto fix linting error feature
=> Fixed more eslint errors

scss/foundation-styles/type.scss
=> Updated H4 line-height

assets/glyphs/search-focus.svg, assets/glyphs/search.svg, components/help-dropdown/help-dropdown.jsx, components/search-tab-group/search-tab-group.jsx, pages/search/search.jsx, pages/search/search.scss, scss/foundation-styles/glyphs.scss, scss/foundation-styles/mixins.scss, scss/main.scss, scss/mixin.scss, scss/shared.scss
**Related Prs**: #1103, #1104 
**Master PR**: #1101 
_This PR updates the search and dropdown styles according to design._
View Changes Here ➡️ https://network-pulse-staging-pr-1102.herokuapp.com/search
=> Search Bar Updates

pages/add/add.jsx
=> More sign-in specificity

components/help-dropdown/help-dropdown.jsx, components/search-tab-group/search-tab-group.jsx, main.jsx, pages/search/search.jsx
**Related Prs**: #1102, #1103 
**Master PR**: #1101 
_This PR redirects the homepage to the search component instead of Featured and adds the 'Learn More' tagline._
View Updates Here  👉  https://network-pulse-staging-pr-1104.herokuapp.com/
=> Homepage redirect

components/footer/footer.jsx
Related to https://github.com/mozilla/foundation.mozilla.org/issues/3319
=> Add 'Cookies' link to footer

components/form-fields/dynamic-checkbox-group.jsx, components/form-fields/help-types.jsx, package-lock.json, pages/add/add.jsx, pages/add/add.scss, pages/add/form/basic-info-fields.js, pages/add/form/detail-info-fields.js, pages/add/form/get-help-fields.js, pages/profile-edit/form/fields.js, pages/profile-edit/profile-edit.jsx, pages/profile-edit/profile-edit.scss, scss/form.scss, scss/main.scss, scss/mixin.scss, scss/overrides/_glyphs.scss, scss/overrides/_variables.scss
Closes #1059
https://network-pulse-staging-pr-1115.herokuapp.com/add
https://network-pulse-staging-pr-1115.herokuapp.com/myprofile
=> Entry/Profile Form Updates

components/navbar/navbar.jsx, main.jsx, pages/add/add.jsx, pages/bookmarks.jsx, pages/entry.jsx, pages/issue.jsx, pages/issues/issues.jsx, pages/moderation-search/moderation-search.jsx, pages/profile-edit/profile-edit.jsx, pages/profile.jsx, pages/search/search.jsx, pages/single-filter-criteria-page.jsx
Related issue/PR: #1112, #1079 
Page Checklist for Reviewer:
=> Removed container class from main.jsx and added it to individual components

components/footer/footer.scss, main.jsx, scss/main.scss
=> Main container fix

main.jsx
=> #Main spacing content fix #2

components/bio/bio.scss
Fixes issues like https://www.mozillapulse.org/profile/2099
=> Add max width to images inside bio page

assets/glyphs/dismiss-focus.svg, assets/glyphs/dismiss.svg, components/search-tab-group/search-tab-group.jsx, pages/search/search.jsx, pages/search/search.scss, scss/foundation-styles/glyphs.scss
Related issue: #1117 
@natalieworth I made the `x` icon to be `16px * 16px` across all screen sizes to stick with other existing icon style on the site. On mockup it's 16x16 on desktop and 14x14 on mobile (also note that 14x14 might be too small for a control on mobile)
=> Add x button to homepage search input box

components/bio/bio.jsx, components/footer/footer.jsx, components/navbar/navbar.jsx, pages/search/search.jsx, scss/foundation-styles/glyphs.scss, scss/main.scss, scss/overrides/_glyphs.scss
Related issue: https://github.com/mozilla/foundation.mozilla.org/issues/3426
=> Update glphy classname

package-lock.json, package.json
=> Minor npm package updates

components/newsletter-sign-up/newsletter-sign-up.jsx, js/basket-signup.js, js/security-headers.js, js/service.js
Related issue: #1118 
Mimicked https://github.com/mozilla/foundation.mozilla.org/pull/126/files with some changes (see my inline GitHub comment)
=> Newsletter signup - POST to Basket directly

components/project-card/project-card.scss
=> Remove gray tint to proejct images & add light gray border to project images on list view

.stylelintrc, .stylelintrc-colors.js, components/join-us-modal/join-us-modal.scss, components/navbar/navbar.scss, components/notification-bar/notification-bar.scss, package-lock.json, package.json, pages/add/add.scss, pages/search/search.scss, scss/foundation-styles/_variables.scss, scss/main.scss, scss/mixin.scss, scss/shared.scss
=> Prettier for stylelint

README.md
=> Be clear about accepting contributions

package-lock.json, package.json
Related issue: #1162 
Another PR to upgrade webpack to v4 to follow as it's not as straightforward.
=> Upgrade webpack to v3

server.js
Related issue: #1068 
- 1st commit - followed this [guide](https://github.com/helmetjs/hsts/blob/master/CHANGELOG.md#deprecated) to fix the `setIf` deprecation warning
- 2nd commit - shifted some code around to make this `server.js` more readable
=> Fix 'setIf' deprecation warning

components/project-card/project-card-simple.jsx
Related issue: #1153 
https://network-pulse-staging-pr-1174.herokuapp.com/moderation
=> Add post date to moderation view

package-lock.json, package.json
=> Update 'express', 'mofo-bootstrap', and 'react-tag-autocomplete' to latest version

README.md, app.json, js/review-app-slack-webhook.js
Things to do when the PR is merged:
Ref: mozillafoundation/mofo-devops#728
=> update docs, reviewapp admin script and app.json

js/review-app-slack-webhook.js, package-lock.json, package.json
Closes #1245 
Replaced `request` by node's build-in `https` + Promise.
@patjouk can you verify that my PR doesn't break the script?
=> Removed 'request' as dependency

app.jsx, package-lock.json, package.json
Close #1151 
`@babel/polyfill` includes polyfills for `Object.assign()` and `Promise`.
=> Use @babel/polyfill to fix a bunch of IE issues

scss/foundation-styles/buttons.scss, scss/foundation-styles/type.scss
- https://github.com/mozilla/foundation.mozilla.org/issues/4136
- https://github.com/mozilla/foundation.mozilla.org/issues/4158
- https://github.com/mozilla/foundation.mozilla.org/pull/4206/files
- https://github.com/mozilla/foundation.mozilla.org/pull/4263/files
=> Update some font styles so they align with changes made to the brand style guide

README.md, package.json
=> Use 'heroku-postinstall' instead of 'postinstall'

.github/ISSUE_TEMPLATE/bug_report.md
Update heading styling to improve readability.
=> Update bug report markdown to improve readability

js/review-app-slack-webhook.js
Removing `attachments` to replace it with the new `blocks` syntax.
ref mozillafoundation/mofo-devops#756
=> Slack bot - Replace attachments by blocks

js/security-headers.js
Related issue: https://github.com/mozilla/foundation.mozilla.org/issues/5976
=> Whitelist GTM scripts

js/security-headers.js
security headers were missing some CSP values
=> Missing CSP values

README.md, config/default.localhost.env.txt
See https://github.com/mozilla/network-pulse-api/pull/783
=> make things runnable again

package.json
=> Added node version to package.json
