- index.html
- js/project-card.js
Fixes #57 
To QA, search for "Mozfest"... you should see a Mozilla wordmark (I used it as the thumbnail) on the card. Don't worry about styling tweaks as those will be tackled in another ticket.
/cc @cadecairos @acabunoc
> Display thumbnail image if any

- css/projects.css
Fixes #110 
- 2-column layout on 650px to 950px wide screens
- 3-column layout on 950px+ wide screens
- project cards are now centered
> 2-column layout on medium ish screen size

- css/projects.css
- index.html
- js/project-card.js
- js/pulse.js
- js/views-manager.js
Fixes #58 
Added more metadata(`tags` `issues` `program` `type`) to Project Card but do not make them visible on UI (see https://github.com/mozilla/network-pulse/issues/58#issuecomment-235935083)
Note that this PR is about making values of  `tags`, `issues`, `program`, and `type` searchable with the **current** search setup (i.e., search through `textContent` within Project Card)
/cc @acabunoc @cadecairos 
---
To test, you can temporary remove class `hidden-meta` from `index.html`. The additional metadata will then show on UI, within Project Card. Stay on the Features tab and search for "literacy", you should see 3 matching projects instead of 1 (<-- the result you will get if you try the same search term on https://mozilla.github.io/network-pulse/)
> Added more metadata(`tags` `issues` `program` `type`)

- css/projects.css
- index.html
- js/favourites-manager.js
- js/project-card.js
- js/search.js
- js/views-manager.js
Fixes #137
- default view mockup: https://redpen.io/gwd26a320b45fb5b71
- with an issue button selected: https://redpen.io/jk994520064b080f30
- toggling off an issue button goes back to the default view.
I will update the QA list and attach a copy below.
@acabunoc @cadecairos 👀 ? 💐 
---
To test, you can
1. add `<%- issues %>` as line 94 in `index.html`. This will display the `issues` meta on the project card.
2. go to Issues Tab. Click on any issue button and see if the filtered list matches the issue you have selected.
> Implemented Issues Tab

- index.html
- js/favourites-manager.js
- js/project-card.js
- js/pulse.js
- js/search.js
- js/views-manager.js
Fixed #27 
Note that this PR only covers a subset of the things listed in https://github.com/mozilla/network-pulse/issues/69 since many features mentioned there haven't been implemented yet (not MVP).
@cadecairos @acabunoc 👀 plz? 🌹 
---
To test, I `ngrok` it and check the [real time dashboard](https://analytics.google.com/analytics/web/#realtime/rt-event/a49796218w120928703p126521218/%3Fmetric.type%3D1%26filter.list%3D40%3D%3DSign%252520Up%252520Link%3B/) on GA
> Added Google Analytics

- js/pulse.js
Fixes #148
Since we are generating `id` based on `timestamp`, any project without `timestamp` should be ignored.
/cc @cadecairos @acabunoc :
> Ignored any project without timestamp

- css/projects.css
- index.html
- js/nav-items-manager.js
- js/project-card.js
- js/search.js
- js/utility.js
- js/views-manager.js
Fixes #175. 
/cc @cadecairos @acabunoc 
🔸 🔶 🔸 🔶 🔸 🔶 🔸 🔶 🔸 🔶 🔸 🔶 🔸 🔶 🔸 🔶 🔸 🔶 🔸 🔶 🔸 🔶 🔸 🔶 
Three scenarios:
🌴 🌷 🌴 🌷 🌴 🌷 🌴 🌷 🌴 🌷 🌴 🌷 🌴 🌷 🌴 🌷 🌴 🌷 🌴 🌷 🌴 🌷
> New detail view and flow

- css/projects.css
- index.html
Fixes #88 , UI/CSS changes
what we have now
bottom align buttons and controls
/cc @cadecairos ( I think @acabunoc is still on PTO? 😉 )
> Bottom align buttons and controls

- css/projects.css
- index.html
- js/project-card.js
Fixes #200 
on detail view
clicking on the hyperlink icon will expose an input box prefilled with project direct url (read only)
/cc @acabunoc @cadecairos review plz? 🐹 😉 🍎 🍊 🍉
> Added share button to details view

- css/projects.css
- index.html
- js/pulse.js
- js/views-manager.js
Fixes #111
@cadecairos @acabunoc ✨ 
I removed a bunch of legacy code in this PR and I left inline comments for them.
Other than that, major things I did in this PR
- removed `PulseMaker.renderApp` method and moved relevant code to `PulseMaker.init` instead
- added callback to `PulseMaker.getData`
- added `PulseMaker._projectsUpdated` property
- closing "add new" form triggers data fetching
- on **tab switch**, check to see if there's updated project data available. Load updated data if exists.
To test,
1. try adding a new project
2. close form
3. navigate to the Latest Tab and see if your project appears
> Load submitted project on tab switch

- js/pulse.js
Fixes #217
Fixed inconsistent project ID bug. Now we just use the timestamp Google API returns as is plus slugify it. (with no other parsing or conversion involved)
> Fixed inconsistent ID bug.

- server.js
our heroku emergency fix forgot to ensure that there is a default port in case neither the env.generates.json nor the process environment contain PORT values.
> add default port to server script

- js/security-headers.js
- server.js
1. Fix https redirect that was being shorted by express.static
2. disable 'x-powered-by' header
3. fix hsts header
4. modify CSP to explicitly forbid framing
5. Add helmet.frameguard
> Security Upgrades

- pages/add/add.jsx
- pages/add/form/validator.js
the validators for thumbnail images were kicking in even when no image had been added. This fixes that by making the validation functions pass over "null" image data.
> fix validators kicking in when there is no image

- js/service.js
Fixes #437
Added missing trailing slash to the `/entries/entryID/` API route
> Added missing trailing slash to a API route

- package.json
Windows passes single quotes as "part of the argument", so needs double quotes for these tasks to run properly
> quote fixes for windows

- components/footer/footer.jsx
- components/hint-message/hint-message.jsx
- components/project-card/project-card.jsx
- components/project-list/project-list.jsx
fixes #478 & covers some of #477 
I'm still seeing a warning about `React.PropType` but I think it's coming from the modules we are using.
> Migrating away from React.PropType

- components/hint-message/hint-message.jsx
- pages/add/add.jsx
- pages/add/submitted.jsx
- routes.jsx
closes https://github.com/mozilla/network-pulse/issues/504, closes https://github.com/mozilla/network-pulse/issues/507
This adds in a new route for submittion entries that are not immediately set to `is_approved`.
- user hits up "add" page
- user submits entry data
- if the entry is immediately `is_approved` (e.g. this is a staff post) then the user is redirect to their entry's URL (same as before)
- if the entry is **not** immediate `is_approved` (e.g. normal user) then they are sent to `/submitted` and presented with a thank you screen and a link to where their entry will exist once we approve it.
> special route for posts pending approval

- pages/entry.jsx
Closes https://github.com/mozilla/network-pulse/issues/506
This change adds some reporting to the `/entry` page so that when an entry is a 404, or it's filtered as a 404 because it's pending approval, the page is not just a blank page, but informs the user that this entry is not currently available.
This PR is built on top of #509
> Give an "entry unavailable" notice on 404 and pending approval

- components/project-card/project-card.jsx
- pages/bookmarks.jsx
fixes https://github.com/mozilla/network-pulse/issues/512 by resolving a scoping issue where ES6 syntax is used for JSX but the event handling does not use `evt => this.doThing(evt)` to preserve `this` scoping.  It also removes a reference to `this.fetchData()` in the bookmark page, which didn't exist and was probably a copy-paste leftover.
> fix event scoping and nonexistent function calls

- components/project-list/project-list.jsx
Fixes #566 
```
Category : Nav link
Action : Clicked
Label : [path] + 'more' (e.g. '/Featured more')
```
To QA:
1. checkout this PR
2. go to `js/analytics.js`
3. add `{debug: true}` to line 20
```js
ReactGA.initialize(`UA-87658599-4`, {debug: true});
```
4. go to a project list page, e.g., /latest
5. click on the "View more" button near page bottom
6. check your browser console if there are logs like the following screencap 
Ignore the weird lettercasing. We'll handle it in [this ticket](https://github.com/mozilla/network-pulse/issues/574).
> Track 'View more' button clicks

- routes.jsx
- scss/main.scss
Fixes #511 
@ScottDowne Alan mentioned you could help with some PR reviews so I'm assigning this one to you (thanks!) This PR should be pretty straightforward as it just removes code.
For reference, this is what the splash page looks like when user visits the site (https://mzl.la/pulse) the first time (a toggle flag is remembered in `localStorage`). Now we want to remove the splash screen altogether.
> Removes splash page

- package.json
- pages/add/form/detail-info-fields.js
Fixes #568 
---
Note: confirm if we want to push for oneWord tags (no spaces) or multi-word tags (with spaces) are fine
> Removed interim fix for tag field

- components/bookmark-control.jsx
- components/nav-link/nav-link.jsx
- components/project-card/meta/get-involved.jsx
- components/project-card/meta/thumbnail.jsx
- components/project-card/meta/title.jsx
- components/project-card/project-card-detailed.jsx
- components/project-card/project-card-simple.jsx
- components/project-list/project-list.jsx
- pages/add/add.jsx
- pages/bookmarks.jsx
- pages/search/search.jsx
- routes.jsx
Related to #574 
See https://docs.google.com/spreadsheets/d/1x-CP_HYaAs3oRv2cjbSFu8w5Z938E4cyHQ3hvh17c6c/edit#gid=1060389854 for the list of things we are tracking.
Some notes:
- For this pass we are tracking "submit error" whenever form validation fails. (no GA label needed for now)
- As "login" links redirect users to Google page, to test "login" related GA events you might need to set up breakpoints in debugger in order to see the logs in console.
---
To QA:
1. check out this PR
2. go to `js/analytics.js`
3. add `{debug: true}` to line 20
```js
ReactGA.initialize(`UA-87658599-4`, {debug: true});
```
4. open your dev tool console
5. start testing
6. look for logs in the console that start with `[react-ga]` and see if the event category/action/label match what we have on [this …
> GA event cleanup

- components/form-fields/help-types.jsx
- components/form-fields/issues.jsx
- js/app-user.js
- pages/add/add.scss
- pages/add/form/detail-info-fields.js
- pages/add/form/get-help-fields.js
- pages/profile-edit/form/fields.js
- pages/profile-edit/profile-edit.jsx
- pages/profile-edit/profile-edit.scss
- routes.jsx
- scss/form.scss
- scss/main.scss
❗️ **This is a feature branch against another feature branch `edit-profile-page`.**
Related to #626 .
Mockup: https://redpen.io/bk7c2a3cbaafdcd47a
Instead of filing a huuuuuuuuuge PR I'm trying to tackle #626 in stages. This PR **only** covers the following
- added the route `/myprofile`
- added UI elements to the `/myprofile` page (no functionality, just making sure fields are there in the form)
- some CSS refactor and changes
Functionality bits like event handlers related to the form submission and form validations are not covered in this PR.
Note:
To log in locally... log in via http://test.example.com:8000/admin/login/?next=/admin/ instead. The "sign in" link on Pulse front end doesn't work locally due to some Google Client setup (I can't recall the actual reason. Will need to get …
> Edit profile page UI only

- components/bio/bio.jsx
- components/project-card/project-card-detailed.jsx
- js/service.js
- pages/profile.jsx
- routes.jsx
(Note: this is a feature branch on top of the WIP `all-things-profile-related` branch)
Fixes #625 
To test,
1. Go to a detail entry page (e.g, http://localhost:3000/entry/55 )
2. Near the bottom of the left column you will see a line like `Added [date posted] by [name]`
3. Click on the [name] and see if that brings you to that person's profile page
> Link entry submitter's name to profile page

- components/hint-message/hint-message.jsx
- components/hint-message/hint-message.scss
- components/loading-notice.jsx
- components/project-list/project-list.jsx
- pages/entry.jsx
- pages/my-profile.jsx
- pages/not-found.jsx
- pages/profile-edit/profile-edit.jsx
- pages/public-profile.jsx
- routes.jsx
Fixes [#685](https://github.com/mozilla/network-pulse/issues/685#issuecomment-327913388) .
**Public profile page (`/profile/<profileid>`)**
**My profile page(`/profile/me`)**
**Edit profile page**
---
@gvn PR isn't very small, though the changes are not very complicated. Reviewing code commit by commit might make this PR easier to review.
> Profile pages - 404 and 'please log in' handling

- pages/not-found.jsx
seems like we can't really set default value for `children` using `defaultProps`... so... here's the fix!
> Make sure fallback hint message is properly set on <NotFound> component

- package.json
- pages/search/search.jsx
This uses an updated DebounceInput component, which as of v3 offers a direct link into the textfield that it uses so that we can blur it without needing to hack around it.
Fixes #492
> blur the input on Enter

- components/form-fields/dynamic-checkbox-group.jsx
- pages/add/add.jsx
https://github.com/mozilla/network-pulse/commit/a5435ad827e11e1c29c88071671600f636c02611 introduced ES6 syntax that broke React's old way of binding "this", leading to an inability to post entries.
> fix callback this-binding

- pages/public-profile.jsx
Related to #813 
1. (depends on which API instance you are connecting to) Go to Django dashboard and find out what your `profile_id` is: 
- http://test.example.com:8000/admin/profiles/userprofile/ 
- OR https://network-pulse-api-staging.herokuapp.com/admin/profiles/userprofile/
2. Pulse frontend: Go to http://test.example.com:3000/profile/<your_profile_id>
3. See if the "Sign out" link works
> Sign out link bug on user's own public profile

- components/navbar/navbar.jsx
- components/navbar/navbar.scss
Related to #731
> - reduce height of the entire header (about from 220px to 180px)
> - make '+' icon hover state smooth like on Foundation site, rather than sudden jump
> - selected state for menu item should be underlined
> - link the little 'm' to the Feature page (like the full logo)
> - here's the logo in black pulse-logo.svg.zip
Not sure what this file is for. Might be for logo hover state? I checked a few Mozilla sites and none of them inverses logo colour on hover state. --- let's discuss this further in a followup ticket.
> Bug: (maybe open a new ticket for this?)
> If open the menu at a narrow screen width and then make it wide, the menu looks like this (seems ok on Foundation site):
This is probably not worth fixing as it is a rare case and there's probably no "clean" way of …
> Nav bar tweaks

- components/project-card/project-card-detailed.jsx
- components/project-card/project-card.scss
Related to #790 
Tiny PR... to test, just to go detailed view for any entry and see if you still get 2 divider lines before the "correction?" link on mobile.
> Remove extra divider on mobile

- components/bio/bio.jsx
- components/nav-link/nav-link.jsx
- components/project-card/meta/creators.jsx
- components/project-card/meta/get-involved.jsx
- components/project-card/project-card-detailed.jsx
- components/project-card/project-card-simple.jsx
- js/analytics.js
Related to #746 #844 
To test locally
1. go to `js/analytics.js` and add `{debug: true}` as the 2nd parameter to line 20.
i.e., ```ReactGA.initialize(`UA-87658599-4`, {debug: true});```
2. open console on your browser dev tool
3. look for "react-ga" logs and use below as checklist
e.g., this should NOT happen <img width="832" alt="screen shot 2017-11-20 at 5 31 30 pm" src="https://user-images.githubusercontent.com/2896608/33050258-c29ac1f2-ce18-11e7-999b-38d017831dae.png">
`eventLabel` should be `[name of profile owner] - type of social media icon you clicked`
e.g., <img width="1050" alt="screen shot 2017-11-20 at 5 40 38 pm" src="https://user-images.githubusercontent.com/2896608/33050490-f598ae06-ce19-11e7-94f1-dac0b66c840d.png">
`eventLabel` should be `[name of project] - [name of …
> GA changes

- pages/add/add.scss
- pages/add/form/basic-info-fields.js
- scss/form.scss
- scss/main.scss
Related to #806 
---
@kristinashu 
We can't smartly and easily position error message and character counter on the same line because each of them belongs to a different parent element (green box and blue box). Do you think removing "x This field cannot be left blank" and just showing a red "0/80" is enough?
> Form error styling tweaks

- config/default.env
Based on @cadecairos 's suggestion
> connect at https://pulse-api.mofostaging.net rather than the heroku URL
our OAuth setup doesn't provide a callback url in the request, so Google automatically selects the first one we configured, and if the host doesn't match the origin of your original request, it gets paranoid
> Changed default api url

- contribute.json
- package.json
- server.js
Related to #875 
Not sure what to do with the SRI part. I couldn't generate integrity for [`https://platform.twitter.com/widgets.js`](https://github.com/mozilla/network-pulse/blob/master/server.js#L94) using [SRI Hash Generator](https://www.srihash.org/)
> Error: this resource is not eligible for integrity checks. See http://enable-cors.org/server.html
> Bumped up Pulse's Observatory score

- main.jsx
- pages/issue.jsx
Related to #852 
Only these 5 child routes on `/issues/` are supported
- `/issues/online-privacy-and-security`
- `/issues/open-innovation`
- `/issues/decentralization`
- `/issues/web-literacy`
- `/issues/digital-inclusion`
Child route that includes the encoded issue name (e.g., `/issues/Open%20Innovation` should be redirected to the corresponding supported route `/issues/open-innovation`)
Any other child routes on `/issues/` will be redirected to `/issues` page.
> Better /issues routes handling

- main.jsx
- pages/single-filter-criteria-page.jsx
Related issue: #899 
Summary: As suggested by @mmmavis at #899, the router match params were being encoded twice, and thus now thety are decoded once before setting it in `SingleFIleCriteriaPage`. 
Also, since they are already decoded now, they aren't further decoded in the `pages/single-filter-criteria-page.jsx` file.
@mmmavis Please review
> removed double encoding, fixes help routes; Fixes #899

- components/bio/bio.jsx
- components/bio/bio.scss
Related issue: #805 
Summary : @mmmavis , I have made the changes and as the icons were `font-awesome` icons so I only increased their `font-size` to `40px`.
Here is a screenshot of the changes made
and for desktop view
> Social media Icon sizes have been increased to 40px

- components/project-card/meta/get-involved.jsx
- js/service.js
Related issue: #910 
Summary: As suggested by @alanmoo and @xmatthewx , the required changes have been made and they reflect too in the following preview. Refer #910 for more details about the same.
Please preview @alanmoo and @xmatthewx  :smile:
> Clean help urls : Fixes #910

- pages/add/form/basic-info-fields.js
- pages/profile-edit/form/fields.js
Related issue: #770
Summary: There already exists a character count for the `Title` field. Thus I have used the same thing for `Bio` and `Description` fields
GIF:
@xmatthewx, please review.
> Show character counts on fields that have character limit

- components/profile-tab-group/profile-tab-group.jsx
Just did a prod push and I started getting this error when visiting some profiles. I assumed every profile returned from API call would have this `entry_count` property... I guess I was wrong!
> Set default value for a required prop 'entryCount'

- README.md
- config/default.env
- js/env-server.js
Related to #944 
@alanmoo I couldn't decide if we should do this by updating the env var or updating the strings in https://github.com/mozilla/network-pulse/blob/master/js/service.js#L177-L272 so they have `/v2` in the API endpoints. Thoughts?
> Use Pulse API v2

- components/profile-project-tab/profile-project-tab.jsx
Related to #959
First project listed on that favs tab should have the largest `id`. You can verify by hovering over the project card and check the url shown in browser.
In the following screencap, the first project has id `373`
> Showed newest created project first on Profile Favs tab

- README.md
- config/default.env
- package-lock.json
- server.js
Related issue: https://github.com/MozillaFoundation/mofo-devops/issues/599
Summary: Updates the HTTPS redirect to also redirect to an enforced hostname. The middleware now only applies if `NODE_ENV === 'production'`, to simplify the logic when running the middleware. also enables the `trust proxy` setting in express when in prod, which automatically sets `req.protocol` to the value of `x-forwarded-proto`, simplifying the check in the middleware.
> Hostname redirect

- README.md
- config/default.env
- js/app-user.js
- js/env-server.js
- js/service.js
Front-end fix for https://github.com/mozilla/network-pulse-api/pull/413 and the api side must land first.
Simply separates out the login/logout urls since every other pulse api url has a prefix of `/api/pulse` whereas these two routes do not.
> Update auth routes to use new api auth system

- README.md
Summary:
david-dm.org appears to have been [down for over a month and a half](https://github.com/alanshaw/david-www/issues/423)
> remove david-dm dependency badges

- package.json
Heroku is changing is default: if a `build` step is present, it will be used, which we don't want.
```
Detected both "build" and "heroku-postbuild" scripts
Running heroku-postbuild
> network-pulse@2.0.0 heroku-postbuild /tmp/build_6107274ab6befd90b34601a814546d24
> echo Skip builds on Heroku
```
> Update package.json: do not run build on Heroku

- components/footer/footer.jsx
The contact form is getting a bunch of people looking for Mozilla related help. I suspect they're coming from this footer. The link is still up in entries for edits.
Related issue:
Summary:
If you don't know who to ask for a review, try @alanmoo or @xmatthewx. If you do, please delete this line.
> Remove "contact" link from footer

- js/service.js
- pages/add/form/creators.js
Fixes two things I noticed:
1. Autocomplete from creators used `/profiles?name=` instead of `/profiles/?name=...&basic=true`. The first one gets a lot of unnecessary data which isn't used, so it's a performance drag on the db.
2. We attached the generic profile image in the autocomplete to every single creator (we used `profile_id` which is something every creator has) whether they were a creator with a profile or a creator without one. This fixes that. My guess is that it was because we didn't fully fix the code when we switched to v2 of the api.
To test:
1. When adding an entry, try to trigger autocomplete for a creator. Check the request to the api and make sure the returned response from the api is an array with each object only containing `id`, `name`, and `is_active`.
2. Choose an …
> Optimize creator autocomplete

- package.json
Remove `heroku-run-build-script` cf https://github.com/MozillaFoundation/mofo-devops-private/issues/205
ref MozillaFoundation/mofo-devops-private#208
> remove unecessary Heroku flag

- scss/main.scss
Related issue: #1066 
This will update all elements with `.btn-link .inline-link` classes to follow `a` link styles. This affects:
1. The dismiss "x" on mobile nav menu
2. Link in text on the bookmarks page
3. Profile sign in/out button
> Updating btn-link styles

- scss/mixin.scss
- scss/overrides/_variables.scss
Closes  #1072 
_*Updated `@mixin link-text-decoration` to `text-decoration: none` default, but underline on hover_
> Update anchor default styles

- scss/overrides/_type.scss
The issue with the anchor styling is coming from `../node_modules/bootstrap/scss/reboot.scss` import on L12 of `main.scss`.  This pr adds an override for site-wide anchor tags. ( Ref: #1094, #1098)
Post 🚀 clean up ticket: #1100
> Found source of <a> underline & updated it

- components/project-card/project-card-detailed.jsx
- components/project-card/project-card-detailed.scss
Related issue: #1130
Summary: Visit button spans full width when Get Involved button isn't there (see [here](https://pulse.mofostaging.net/entry/492)). Fix involves keeping Visit button half width even when Get Involved Button not visible.
p.s. sorry mavis 😭 
_Note_: Commit should say 'bug' fix...not 'big' fix.
> Entry button Fix

- pages/add/add.jsx
Related issue: #1140 
Summary: Added side margin to the error message on 'Add page'
Please review @alanmoo @mmmavis 
Screenshots for change:
> add side-margin for error message on 'Add' page

- package.json
Related issue: PR https://github.com/mozilla/network-pulse/pull/1165
I [accidentally removed this task](https://github.com/mozilla/network-pulse/pull/1165/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L10) in my previous PR. Adding it back now.
> Add back 'heroku-postbuild' npm task

- components/profile-card/profile-card.jsx
Closes #1204 
Removed extra event handler that was probably copied and pasted by mistake. (I cross-checked with our [GA event spreadsheet](https://docs.google.com/spreadsheets/d/1x-CP_HYaAs3oRv2cjbSFu8w5Z938E4cyHQ3hvh17c6c/edit#gid=1060389854) and didn't see any "profile" related event lists)
https://network-pulse-staging-pr-1205.herokuapp.com/people?keyword=mavis
> Fix profile search bug

- js/review-app-slack-webhook.js
Using token in query params are not deprecated.
Related PRs/issues mozillafoundation/mofo-devops-private#297
> Pass github token in headers and not as a query param

- package.json
Related issue: #1264 
Summary: We actually want to hook into `heroku-postbuild`, I missed that detail in my review of #1264
> heroku-postbuild, not heroku-postinstall

- pages/add/form/auto-complete-input.js
- pages/add/form/detail-info-fields.js
- pages/add/form/tag-delimiters.js
- scss/form.scss
Fixed #1360 
I should have been more careful with that Dependabot PR & visited the official `'react-tag-autocomplete` repo for more detailed docs before upgrading that library to v6. 
Note that autocomplete doesn't work for the "creator" field due to an API bug. I've filed a ticket on the API repo.
> Fix regression bugs due to recent 'react-tag-autocomplete' v6 uplift

- README.md
- server.js
Closes #1529
This adds noindex/nofollow/noarchive to our express responses as both an HTTP header and a google-specific meta tag (because of course Google is special, why wouldn't it be).
This relies on an env var `STAGING_SERVER`, which I've already set to `True` on the heroku staging server.
> Add noindex, nofollow, noarchive for staging server

- package-lock.json
- package.json
Closes #1551
Removes the `engines` requirements in both this repo, and uses an updated `react-formbuilder` version, which also removed the `engines` requirements.
> remove 'engines' section because it's no longer necessary

- components/navbar/navbar.jsx
Related issue: https://github.com/mozilla/network-pulse-api/issues/768
Summary: removes wording for "sign up"
> signin only, no signup

- components/newsletter-sign-up/newsletter-sign-up.jsx
Related issue:#1656
This PR adds a new data layer event to the pulse newsletter sign up form at the footer of the app, as well as moves the code within an if statement, to make sure that the event doesnt fire unless the user selects the privacy consent checkbox.
**Note:**
Per instructions in #1656, I have removed the language and country parameters, since the sign up form in pulse does **not** use these.
```
dataLayer code:
// Mozilla Foundation + Torchbox - 2022
// dataLayer push for newsletter signup form submission
window.dataLayer = window.dataLayer || [];
window.dataLayer.push({
event: 'form_submission',
form_type: 'newsletter_signup', // type of form. should be static in this case
form_location: 'header', // update with location of form in page -- either 'header' or 'footer', …
```
>  updated to use data layer + only fire when checkbox is checked

- js/analytics.js
- js/security-headers.js
- server.js
Made changes based on https://docs.google.com/document/d/1IbfNfn0HUoJ94qDTWiwZjxWmy8ZzisyilGtxOhR5xNc/edit
Related to ticket https://github.com/mozilla/foundation.mozilla.org/issues/9587
- It's easier to review this PR without whitespace changes: https://github.com/mozilla/network-pulse/pull/1661/files?w=1
- This is how I test this PR. Please advise if you have a better way to test it. Thanks!
- run project locally
- hard refresh the page
- open dev tool's Network tab, go to `HTML` subtab, find the response with `initiator` type `document`, and look for `nonce-` value in CSP of the response header
- right click on the page to `view source`, look for `nonce` value
- verify the two nonce values match
- if the values match, a few extra `<script>` from GA/GTM should be injected into `<head>`. …
> Added nonce & implemented GTM and CSP changes 
